# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='my_user',
        ),
    ]
