# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_auto_20170916_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to='static/files/'),
        ),
    ]
